GrundeinstellungenTab="Impostazioni Generali"
apiUserIdLabel="API User ID"
apiUserKeyLabel="API User Key"
spaceIdLabel="Space Id"
resourceVersionLabel="Versione Risorsa"
orderRetryStatusLabel="ID degli stati, per ulteriori tentativi di pagamento"
orderRetryStatusTooltip="Consente di definire gli stati dell'ordine che consentono di selezionare un diverso metodo di pagamento e riprovare. � possibile separare pi� stati da un punto e virgola &quot;;&quot;."
refundSuccessfulStatusLabel="ID di stato per i rimborsi andati a buon fine"
refundFailedStatusLabel="ID stato per rimborsi non riusciti"
confirmationInvoiceLabel="Consenti ai clienti di scaricare la fattura"
confirmationPackingSlipLabel="Consenti ai clienti di scaricare il documento di trasporto"
enablePaymentFetch="Abilita il recupero dei possibili metodi di pagamento"

BankTransferTab=Bank Transfer
BankTransferActiveLabel=Abilitato
BankTransferTitleLabel=Titolo
BankTransferDescriptionLabel=Descrizione
BankTransferFeeLabel=Tassa
BankTransferIconUrlLabel=URL dell'icona (facoltativo)
CreditDebitCardTab=Credit / Debit Card
CreditDebitCardActiveLabel=Abilitato
CreditDebitCardTitleLabel=Titolo
CreditDebitCardDescriptionLabel=Descrizione
CreditDebitCardFeeLabel=Tassa
CreditDebitCardIconUrlLabel=URL dell'icona (facoltativo)
DirectDebitSepaTab=Direct Debit (SEPA)
DirectDebitSepaActiveLabel=Abilitato
DirectDebitSepaTitleLabel=Titolo
DirectDebitSepaDescriptionLabel=Descrizione
DirectDebitSepaFeeLabel=Tassa
DirectDebitSepaIconUrlLabel=URL dell'icona (facoltativo)
EpsTab=EPS
EpsActiveLabel=Abilitato
EpsTitleLabel=Titolo
EpsDescriptionLabel=Descrizione
EpsFeeLabel=Tassa
EpsIconUrlLabel=URL dell'icona (facoltativo)
IDealTab=iDeal
IDealActiveLabel=Abilitato
IDealTitleLabel=Titolo
IDealDescriptionLabel=Descrizione
IDealFeeLabel=Tassa
IDealIconUrlLabel=URL dell'icona (facoltativo)
InvoiceTab=Invoice
InvoiceActiveLabel=Abilitato
InvoiceTitleLabel=Titolo
InvoiceDescriptionLabel=Descrizione
InvoiceFeeLabel=Tassa
InvoiceIconUrlLabel=URL dell'icona (facoltativo)
OnlineBankingTab=Online Banking
OnlineBankingActiveLabel=Abilitato
OnlineBankingTitleLabel=Titolo
OnlineBankingDescriptionLabel=Descrizione
OnlineBankingFeeLabel=Tassa
OnlineBankingIconUrlLabel=URL dell'icona (facoltativo)
PayPalTab=PayPal
PayPalActiveLabel=Abilitato
PayPalTitleLabel=Titolo
PayPalDescriptionLabel=Descrizione
PayPalFeeLabel=Tassa
PayPalIconUrlLabel=URL dell'icona (facoltativo)
PostFinancePayTab=Post Finance Pay
PostFinancePayActiveLabel=Abilitato
PostFinancePayTitleLabel=Titolo
PostFinancePayDescriptionLabel=Descrizione
PostFinancePayFeeLabel=Tassa
PostFinancePayIconUrlLabel=URL dell'icona (facoltativo)
Przelewy24Tab=Przelewy24
Przelewy24ActiveLabel=Abilitato
Przelewy24TitleLabel=Titolo
Przelewy24DescriptionLabel=Descrizione
Przelewy24FeeLabel=Tassa
Przelewy24IconUrlLabel=URL dell'icona (facoltativo)
WeroTab=Wero
WeroActiveLabel=Abilitato
WeroTitleLabel=Titolo
WeroDescriptionLabel=Descrizione
WeroFeeLabel=Tassa
WeroIconUrlLabel=URL dell'icona (facoltativo)
KlarnaPayNowTab=Klarna Pay Now
KlarnaPayNowActiveLabel=Abilitato
KlarnaPayNowTitleLabel=Titolo
KlarnaPayNowDescriptionLabel=Descrizione
KlarnaPayNowFeeLabel=Tassa
KlarnaPayNowIconUrlLabel=URL dell'icona (facoltativo)
KlarnaPayLaterTab=Klarna Pay Later
KlarnaPayLaterActiveLabel=Abilitato
KlarnaPayLaterTitleLabel=Titolo
KlarnaPayLaterDescriptionLabel=Descrizione
KlarnaPayLaterFeeLabel=Tassa
KlarnaPayLaterIconUrlLabel=URL dell'icona (facoltativo)
KlarnaSliceItTab=Klarna Slice It
KlarnaSliceItActiveLabel=Abilitato
KlarnaSliceItTitleLabel=Titolo
KlarnaSliceItDescriptionLabel=Descrizione
KlarnaSliceItFeeLabel=Tassa
KlarnaSliceItIconUrlLabel=URL dell'icona (facoltativo)
