BankTransferTitle="Bank Transfer"
BankTransferDescription = ""
BankTransferIconUrl = ""

CreditDebitCardTitle="Credit / Debit Card"
CreditDebitCardDescription = ""
CreditDebitCardIconUrl = ""

DirectDebitSepaTitle="Direct Debit (SEPA)"
DirectDebitSepaDescription = ""
DirectDebitSepaIconUrl = ""

EpsTitle="EPS"
EpsDescription = ""
EpsIconUrl = ""

IDealTitle="iDeal"
IDealDescription = ""
IDealIconUrl = ""

InvoiceTitle="Invoice"
InvoiceDescription = ""
InvoiceIconUrl = ""

OnlineBankingTitle="Online Banking"
OnlineBankingDescription = ""
OnlineBankingIconUrl = ""

PayPalTitle="PayPal"
PayPalDescription = ""
PayPalIconUrl = ""

PostFinancePayTitle="Post Finance Pay"
PostFinancePayDescription = ""
PostFinancePayIconUrl = ""

Przelewy24Title="Przelewy24"
Przelewy24Description = ""
Przelewy24IconUrl = ""

WeroTitle="Wero"
WeroDescription = ""
WeroIconUrl = ""

KlarnaPayNowTitle="Klarna Pay Now"
KlarnaPayNowDescription = ""
KlarnaPayNowIconUrl = ""

KlarnaPayLaterTitle="Klarna Pay Later"
KlarnaPayLaterDescription = ""
KlarnaPayLaterIconUrl = ""

KlarnaSliceItTitle="Klarna Slice It"
KlarnaSliceItDescription = ""
KlarnaSliceItIconUrl = ""

