GrundeinstellungenTab="Grundeinstellungen"
apiUserIdLabel="API Benutzer ID"
apiUserKeyLabel="API Benutzer Key"
spaceIdLabel="Space Id"
resourceVersionLabel="Resource Version"
orderRetryStatusLabel="Status IDs für weitere Bezahlversuche"
orderRetryStatusTooltip="Ermöglicht die Definition von Bestellstatus, die es erlauben, eine andere Zahlungsmethode zu wählen und es erneut zu versuchen. Mehrere Status können durch ein Semikolon &quot;;&quot; voneinander getrennt werden."
refundSuccessfulStatusLabel="Status ID für erfolgreiche Gutschrift"
refundFailedStatusLabel="Status ID für fehlgeschlagene Gutschrift"
confirmationInvoiceLabel="Kunden erlauben, Rechnungsdokument herunterzuladen"
confirmationPackingSlipLabel="Kunden erlauben, Lieferschein herunterzuladen"
enablePaymentFetch="Aktivieren Sie das Abrufen möglicher Zahlungsmethoden"

BankTransferTab=Bank Transfer
BankTransferActiveLabel=Aktiv
BankTransferTitleLabel=Titel
BankTransferDescriptionLabel=Beschreibung
BankTransferFeeLabel=Gebühr
BankTransferIconUrlLabel=Symbol Url (freiwillig)
CreditDebitCardTab=Credit / Debit Card
CreditDebitCardActiveLabel=Aktiv
CreditDebitCardTitleLabel=Titel
CreditDebitCardDescriptionLabel=Beschreibung
CreditDebitCardFeeLabel=Gebühr
CreditDebitCardIconUrlLabel=Symbol Url (freiwillig)
DirectDebitSepaTab=Direct Debit (SEPA)
DirectDebitSepaActiveLabel=Aktiv
DirectDebitSepaTitleLabel=Titel
DirectDebitSepaDescriptionLabel=Beschreibung
DirectDebitSepaFeeLabel=Gebühr
DirectDebitSepaIconUrlLabel=Symbol Url (freiwillig)
EpsTab=EPS
EpsActiveLabel=Aktiv
EpsTitleLabel=Titel
EpsDescriptionLabel=Beschreibung
EpsFeeLabel=Gebühr
EpsIconUrlLabel=Symbol Url (freiwillig)
IDealTab=iDeal
IDealActiveLabel=Aktiv
IDealTitleLabel=Titel
IDealDescriptionLabel=Beschreibung
IDealFeeLabel=Gebühr
IDealIconUrlLabel=Symbol Url (freiwillig)
InvoiceTab=Invoice
InvoiceActiveLabel=Aktiv
InvoiceTitleLabel=Titel
InvoiceDescriptionLabel=Beschreibung
InvoiceFeeLabel=Gebühr
InvoiceIconUrlLabel=Symbol Url (freiwillig)
OnlineBankingTab=Online Banking
OnlineBankingActiveLabel=Aktiv
OnlineBankingTitleLabel=Titel
OnlineBankingDescriptionLabel=Beschreibung
OnlineBankingFeeLabel=Gebühr
OnlineBankingIconUrlLabel=Symbol Url (freiwillig)
PayPalTab=PayPal
PayPalActiveLabel=Aktiv
PayPalTitleLabel=Titel
PayPalDescriptionLabel=Beschreibung
PayPalFeeLabel=Gebühr
PayPalIconUrlLabel=Symbol Url (freiwillig)
PostFinancePayTab=Post Finance Pay
PostFinancePayActiveLabel=Aktiv
PostFinancePayTitleLabel=Titel
PostFinancePayDescriptionLabel=Beschreibung
PostFinancePayFeeLabel=Gebühr
PostFinancePayIconUrlLabel=Symbol Url (freiwillig)
Przelewy24Tab=Przelewy24
Przelewy24ActiveLabel=Aktiv
Przelewy24TitleLabel=Titel
Przelewy24DescriptionLabel=Beschreibung
Przelewy24FeeLabel=Gebühr
Przelewy24IconUrlLabel=Symbol Url (freiwillig)
WeroTab=Wero
WeroActiveLabel=Aktiv
WeroTitleLabel=Titel
WeroDescriptionLabel=Beschreibung
WeroFeeLabel=Gebühr
WeroIconUrlLabel=Symbol Url (freiwillig)
KlarnaPayNowTab=Klarna Pay Now
KlarnaPayNowActiveLabel=Aktiv
KlarnaPayNowTitleLabel=Titel
KlarnaPayNowDescriptionLabel=Beschreibung
KlarnaPayNowFeeLabel=Gebühr
KlarnaPayNowIconUrlLabel=Symbol Url (freiwillig)
KlarnaPayLaterTab=Klarna Pay Later
KlarnaPayLaterActiveLabel=Aktiv
KlarnaPayLaterTitleLabel=Titel
KlarnaPayLaterDescriptionLabel=Beschreibung
KlarnaPayLaterFeeLabel=Gebühr
KlarnaPayLaterIconUrlLabel=Symbol Url (freiwillig)
KlarnaSliceItTab=Klarna Slice It
KlarnaSliceItActiveLabel=Aktiv
KlarnaSliceItTitleLabel=Titel
KlarnaSliceItDescriptionLabel=Beschreibung
KlarnaSliceItFeeLabel=Gebühr
KlarnaSliceItIconUrlLabel=Symbol Url (freiwillig)
